services:
  simulator:
    build:
      context: ./simulator
    ports:
    # TODO: try different ports cause some weirdos use these ones
      - "127.0.0.1:6080:6080"
    volumes:
      - ./apps/library:/input:ro
    init: true

